### PR TITLE
Request for code review: CSS Grid based Framework 

### PR DESCRIPTION
**Pull request by ferdelvalle**
## Hello TSE and other humans! 🖖🍺

In this project we:
- Create a grid-based framework using sass as frontend technology.
- use features like mixins, variables, and mappings 
- Clone the site www.mercadolibre.com.uy

We appreciate any positive feedback on good practices and clean code on SASS
Any constructive feedback is great!

#### Happy coding! 🚀

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Framework is missing columns breakpoints. Website is not very responsive. Validator errors should be fixed.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!

But there are some more changes required:

* [x] Check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
 
* [x] You have some text in your pull request description section, but it is not the right description.  Correct pull request description should have list of things you implemented in this project.
Look at [this link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) from pathwright for details.

* [x] The defined columns should have breakpoints (example column-large-2).[Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/grid_based_framework/breakpoints_requirement.png)

* [x] Project looks messed up in tablet mode:
image

Same with mobile version:
image
 

### [Optional]
Next classes are optional, but all of frameworks most likely have them:
* Classes for margin top, bottom, left, right, all margins and auto.
* Classes for padding top, bottom, left, right, all margins and auto.
* Classes for float left, right and clearing the floats
* Classes to change the position property of an element to relative, absolute or fixed
* Classes to set vertical alignment as top, bottom or center
* Classes to set horizontal alignment as left, right or center

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Very impressive! Great work using SASS, and love the use of CSS Grid for the framework 👍 .

Also, the page you chose for the demo is a real challenge. Well done! that's the way to push your learning 🚀 .

I can see you have fixed most of the issues pointed out in the previous review, but there is still an issue with the responsiveness of the page as pointed out previously:

- [x] Project looks messed up in tablet mode.

Most of the page is looking good, but please take a look at this screenshot from the [live demo](https://cdn.statically.io/gh/sebastianlujan/grid-based-framework/features/index.html) you provided:
image

By the way, I didn't know about https://statically.io/, It seems like a great resource to have in our toolbox. Thanks for that one 😄 .

**Status:** Request changes.

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team! 

### Great job fixing other TSEs suggestions. :raised_hands: But we are still not there yet. :cry: 

- [x] Ensure to fix the linter errors.

- [x] Let's get rid of the horizontal scroll bar.

scroll

- [x] Your page still looks messy on medium and small screens.

**Medium**


**Small**


**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

**Comment by sebastianlujan** [comment]
Fixed all issues.

**Comment by sebastianlujan** [comment]
> Hi team!
> 
> ### Great job fixing other TSEs suggestions. 🙌 But we are still not there yet. 😢
> * [x]  Ensure to fix the linter errors.
> * [x]  Let's get rid of the horizontal scroll bar.
> 
> scroll
> 
> * [x]  Your page still looks messy on medium and small screens.
> 
> **Medium**
> 
> 
> **Small**
> 
> 
> **Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ 🎉

The problem was solved but statically loaded a previous version, but we solve it using https://raw.githack.com/

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @sebastianlujan , 👋 You have done a great job in this project 👏 UI look great.



> After resolving merge conflit, if you face any of linter errors, then try to resolve that before merge this pr.
----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by sebastianlujan** [comment]
Final branch merges:
features -> development
and development -> master

**Pull request merged**
